# Generated by Django 4.2.5 on 2023-09-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='Subjec',
            new_name='Subject',
        ),
    ]
